//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\Vladimir González\Documents\GitHub\IDS326L-Recetario-Grupo-7\IDS326L-RecetarioSQL-Grupo7\recetaParser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="recetaParserParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IrecetaParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="recetaParserParser.recetaParser"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRecetaParser([NotNull] recetaParserParser.RecetaParserContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="recetaParserParser.receta"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReceta([NotNull] recetaParserParser.RecetaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="recetaParserParser.titulo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTitulo([NotNull] recetaParserParser.TituloContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="recetaParserParser.porciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPorciones([NotNull] recetaParserParser.PorcionesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="recetaParserParser.tiempo_preparacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTiempo_preparacion([NotNull] recetaParserParser.Tiempo_preparacionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="recetaParserParser.tiempo_coccion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTiempo_coccion([NotNull] recetaParserParser.Tiempo_coccionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="recetaParserParser.calorias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCalorias([NotNull] recetaParserParser.CaloriasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="recetaParserParser.ingredientes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIngredientes([NotNull] recetaParserParser.IngredientesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="recetaParserParser.elaboracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElaboracion([NotNull] recetaParserParser.ElaboracionContext context);
}
