//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\Vladimir González\Documents\GitHub\IDS326L-Recetario-Grupo-7\IDS326L-RecetarioSQL-Grupo7\recetaParser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class recetaParserLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		RECETA=1, PORCIONES=2, TIEMPO_PREPARACION=3, TIEMPO_COCCION=4, INGREDIENTES=5, 
		CALORIAS=6, ELABORACION=7, SEP=8, TEXT=9, WORD=10, NUM=11, ORD=12, COMA=13, 
		SK=14, SK1=15, SK2=16;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"RECETA", "PORCIONES", "TIEMPO_PREPARACION", "TIEMPO_COCCION", "INGREDIENTES", 
		"CALORIAS", "ELABORACION", "SEP", "TEXT", "WORD", "NUM", "ORD", "COMA", 
		"SK", "SK1", "SK2"
	};


	public recetaParserLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public recetaParserLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'- RECETA:'", "'- PORCIONES:'", "'- TIEMPO PREPARACION:'", "'- TIEMPO COCCION:'", 
		"'- INGREDIENTES:'", "'- CALORIAS:'", "'- ELABORACION:'", null, null, 
		null, null, null, "','", "'\n'", "'\r'", "'\t'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "RECETA", "PORCIONES", "TIEMPO_PREPARACION", "TIEMPO_COCCION", "INGREDIENTES", 
		"CALORIAS", "ELABORACION", "SEP", "TEXT", "WORD", "NUM", "ORD", "COMA", 
		"SK", "SK1", "SK2"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "recetaParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static recetaParserLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x12', '\xC3', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\t', '\x6', '\t', '\x8F', '\n', '\t', '\r', '\t', '\xE', '\t', 
		'\x90', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\a', '\n', 
		'\x97', '\n', '\n', '\f', '\n', '\xE', '\n', '\x9A', '\v', '\n', '\x3', 
		'\n', '\x5', '\n', '\x9D', '\n', '\n', '\x3', '\v', '\x6', '\v', '\xA0', 
		'\n', '\v', '\r', '\v', '\xE', '\v', '\xA1', '\x3', '\f', '\x6', '\f', 
		'\xA5', '\n', '\f', '\r', '\f', '\xE', '\f', '\xA6', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x6', '\f', '\xAC', '\n', '\f', '\r', '\f', '\xE', 
		'\f', '\xAD', '\x5', '\f', '\xB0', '\n', '\f', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x2', '\x2', '\x12', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', 
		'\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', 
		'\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', 
		'\x10', '\x1F', '\x11', '!', '\x12', '\x3', '\x2', '\x4', '\x4', '\x2', 
		'\x43', '\\', '\x63', '|', '\x3', '\x2', '\x32', ';', '\x2', '\xC9', '\x2', 
		'\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', 
		'\x2', '\x2', '\x3', '#', '\x3', '\x2', '\x2', '\x2', '\x5', '-', '\x3', 
		'\x2', '\x2', '\x2', '\a', ':', '\x3', '\x2', '\x2', '\x2', '\t', 'P', 
		'\x3', '\x2', '\x2', '\x2', '\v', '\x62', '\x3', '\x2', '\x2', '\x2', 
		'\r', 'r', '\x3', '\x2', '\x2', '\x2', '\xF', '~', '\x3', '\x2', '\x2', 
		'\x2', '\x11', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x13', '\x92', '\x3', 
		'\x2', '\x2', '\x2', '\x15', '\x9F', '\x3', '\x2', '\x2', '\x2', '\x17', 
		'\xAF', '\x3', '\x2', '\x2', '\x2', '\x19', '\xB1', '\x3', '\x2', '\x2', 
		'\x2', '\x1B', '\xB5', '\x3', '\x2', '\x2', '\x2', '\x1D', '\xB7', '\x3', 
		'\x2', '\x2', '\x2', '\x1F', '\xBB', '\x3', '\x2', '\x2', '\x2', '!', 
		'\xBF', '\x3', '\x2', '\x2', '\x2', '#', '$', '\a', '/', '\x2', '\x2', 
		'$', '%', '\a', '\"', '\x2', '\x2', '%', '&', '\a', 'T', '\x2', '\x2', 
		'&', '\'', '\a', 'G', '\x2', '\x2', '\'', '(', '\a', '\x45', '\x2', '\x2', 
		'(', ')', '\a', 'G', '\x2', '\x2', ')', '*', '\a', 'V', '\x2', '\x2', 
		'*', '+', '\a', '\x43', '\x2', '\x2', '+', ',', '\a', '<', '\x2', '\x2', 
		',', '\x4', '\x3', '\x2', '\x2', '\x2', '-', '.', '\a', '/', '\x2', '\x2', 
		'.', '/', '\a', '\"', '\x2', '\x2', '/', '\x30', '\a', 'R', '\x2', '\x2', 
		'\x30', '\x31', '\a', 'Q', '\x2', '\x2', '\x31', '\x32', '\a', 'T', '\x2', 
		'\x2', '\x32', '\x33', '\a', '\x45', '\x2', '\x2', '\x33', '\x34', '\a', 
		'K', '\x2', '\x2', '\x34', '\x35', '\a', 'Q', '\x2', '\x2', '\x35', '\x36', 
		'\a', 'P', '\x2', '\x2', '\x36', '\x37', '\a', 'G', '\x2', '\x2', '\x37', 
		'\x38', '\a', 'U', '\x2', '\x2', '\x38', '\x39', '\a', '<', '\x2', '\x2', 
		'\x39', '\x6', '\x3', '\x2', '\x2', '\x2', ':', ';', '\a', '/', '\x2', 
		'\x2', ';', '<', '\a', '\"', '\x2', '\x2', '<', '=', '\a', 'V', '\x2', 
		'\x2', '=', '>', '\a', 'K', '\x2', '\x2', '>', '?', '\a', 'G', '\x2', 
		'\x2', '?', '@', '\a', 'O', '\x2', '\x2', '@', '\x41', '\a', 'R', '\x2', 
		'\x2', '\x41', '\x42', '\a', 'Q', '\x2', '\x2', '\x42', '\x43', '\a', 
		'\"', '\x2', '\x2', '\x43', '\x44', '\a', 'R', '\x2', '\x2', '\x44', '\x45', 
		'\a', 'T', '\x2', '\x2', '\x45', '\x46', '\a', 'G', '\x2', '\x2', '\x46', 
		'G', '\a', 'R', '\x2', '\x2', 'G', 'H', '\a', '\x43', '\x2', '\x2', 'H', 
		'I', '\a', 'T', '\x2', '\x2', 'I', 'J', '\a', '\x43', '\x2', '\x2', 'J', 
		'K', '\a', '\x45', '\x2', '\x2', 'K', 'L', '\a', 'K', '\x2', '\x2', 'L', 
		'M', '\a', 'Q', '\x2', '\x2', 'M', 'N', '\a', 'P', '\x2', '\x2', 'N', 
		'O', '\a', '<', '\x2', '\x2', 'O', '\b', '\x3', '\x2', '\x2', '\x2', 'P', 
		'Q', '\a', '/', '\x2', '\x2', 'Q', 'R', '\a', '\"', '\x2', '\x2', 'R', 
		'S', '\a', 'V', '\x2', '\x2', 'S', 'T', '\a', 'K', '\x2', '\x2', 'T', 
		'U', '\a', 'G', '\x2', '\x2', 'U', 'V', '\a', 'O', '\x2', '\x2', 'V', 
		'W', '\a', 'R', '\x2', '\x2', 'W', 'X', '\a', 'Q', '\x2', '\x2', 'X', 
		'Y', '\a', '\"', '\x2', '\x2', 'Y', 'Z', '\a', '\x45', '\x2', '\x2', 'Z', 
		'[', '\a', 'Q', '\x2', '\x2', '[', '\\', '\a', '\x45', '\x2', '\x2', '\\', 
		']', '\a', '\x45', '\x2', '\x2', ']', '^', '\a', 'K', '\x2', '\x2', '^', 
		'_', '\a', 'Q', '\x2', '\x2', '_', '`', '\a', 'P', '\x2', '\x2', '`', 
		'\x61', '\a', '<', '\x2', '\x2', '\x61', '\n', '\x3', '\x2', '\x2', '\x2', 
		'\x62', '\x63', '\a', '/', '\x2', '\x2', '\x63', '\x64', '\a', '\"', '\x2', 
		'\x2', '\x64', '\x65', '\a', 'K', '\x2', '\x2', '\x65', '\x66', '\a', 
		'P', '\x2', '\x2', '\x66', 'g', '\a', 'I', '\x2', '\x2', 'g', 'h', '\a', 
		'T', '\x2', '\x2', 'h', 'i', '\a', 'G', '\x2', '\x2', 'i', 'j', '\a', 
		'\x46', '\x2', '\x2', 'j', 'k', '\a', 'K', '\x2', '\x2', 'k', 'l', '\a', 
		'G', '\x2', '\x2', 'l', 'm', '\a', 'P', '\x2', '\x2', 'm', 'n', '\a', 
		'V', '\x2', '\x2', 'n', 'o', '\a', 'G', '\x2', '\x2', 'o', 'p', '\a', 
		'U', '\x2', '\x2', 'p', 'q', '\a', '<', '\x2', '\x2', 'q', '\f', '\x3', 
		'\x2', '\x2', '\x2', 'r', 's', '\a', '/', '\x2', '\x2', 's', 't', '\a', 
		'\"', '\x2', '\x2', 't', 'u', '\a', '\x45', '\x2', '\x2', 'u', 'v', '\a', 
		'\x43', '\x2', '\x2', 'v', 'w', '\a', 'N', '\x2', '\x2', 'w', 'x', '\a', 
		'Q', '\x2', '\x2', 'x', 'y', '\a', 'T', '\x2', '\x2', 'y', 'z', '\a', 
		'K', '\x2', '\x2', 'z', '{', '\a', '\x43', '\x2', '\x2', '{', '|', '\a', 
		'U', '\x2', '\x2', '|', '}', '\a', '<', '\x2', '\x2', '}', '\xE', '\x3', 
		'\x2', '\x2', '\x2', '~', '\x7F', '\a', '/', '\x2', '\x2', '\x7F', '\x80', 
		'\a', '\"', '\x2', '\x2', '\x80', '\x81', '\a', 'G', '\x2', '\x2', '\x81', 
		'\x82', '\a', 'N', '\x2', '\x2', '\x82', '\x83', '\a', '\x43', '\x2', 
		'\x2', '\x83', '\x84', '\a', '\x44', '\x2', '\x2', '\x84', '\x85', '\a', 
		'Q', '\x2', '\x2', '\x85', '\x86', '\a', 'T', '\x2', '\x2', '\x86', '\x87', 
		'\a', '\x43', '\x2', '\x2', '\x87', '\x88', '\a', '\x45', '\x2', '\x2', 
		'\x88', '\x89', '\a', 'K', '\x2', '\x2', '\x89', '\x8A', '\a', 'Q', '\x2', 
		'\x2', '\x8A', '\x8B', '\a', 'P', '\x2', '\x2', '\x8B', '\x8C', '\a', 
		'<', '\x2', '\x2', '\x8C', '\x10', '\x3', '\x2', '\x2', '\x2', '\x8D', 
		'\x8F', '\a', '\"', '\x2', '\x2', '\x8E', '\x8D', '\x3', '\x2', '\x2', 
		'\x2', '\x8F', '\x90', '\x3', '\x2', '\x2', '\x2', '\x90', '\x8E', '\x3', 
		'\x2', '\x2', '\x2', '\x90', '\x91', '\x3', '\x2', '\x2', '\x2', '\x91', 
		'\x12', '\x3', '\x2', '\x2', '\x2', '\x92', '\x98', '\x5', '\x15', '\v', 
		'\x2', '\x93', '\x94', '\x5', '\x11', '\t', '\x2', '\x94', '\x95', '\x5', 
		'\x15', '\v', '\x2', '\x95', '\x97', '\x3', '\x2', '\x2', '\x2', '\x96', 
		'\x93', '\x3', '\x2', '\x2', '\x2', '\x97', '\x9A', '\x3', '\x2', '\x2', 
		'\x2', '\x98', '\x96', '\x3', '\x2', '\x2', '\x2', '\x98', '\x99', '\x3', 
		'\x2', '\x2', '\x2', '\x99', '\x9C', '\x3', '\x2', '\x2', '\x2', '\x9A', 
		'\x98', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9D', '\x5', '\x11', '\t', 
		'\x2', '\x9C', '\x9B', '\x3', '\x2', '\x2', '\x2', '\x9C', '\x9D', '\x3', 
		'\x2', '\x2', '\x2', '\x9D', '\x14', '\x3', '\x2', '\x2', '\x2', '\x9E', 
		'\xA0', '\t', '\x2', '\x2', '\x2', '\x9F', '\x9E', '\x3', '\x2', '\x2', 
		'\x2', '\xA0', '\xA1', '\x3', '\x2', '\x2', '\x2', '\xA1', '\x9F', '\x3', 
		'\x2', '\x2', '\x2', '\xA1', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA2', 
		'\x16', '\x3', '\x2', '\x2', '\x2', '\xA3', '\xA5', '\t', '\x3', '\x2', 
		'\x2', '\xA4', '\xA3', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA6', '\x3', 
		'\x2', '\x2', '\x2', '\xA6', '\xA4', '\x3', '\x2', '\x2', '\x2', '\xA6', 
		'\xA7', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xB0', '\x3', '\x2', '\x2', 
		'\x2', '\xA8', '\xA9', '\t', '\x3', '\x2', '\x2', '\xA9', '\xAB', '\a', 
		'\x30', '\x2', '\x2', '\xAA', '\xAC', '\t', '\x3', '\x2', '\x2', '\xAB', 
		'\xAA', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAD', '\x3', '\x2', '\x2', 
		'\x2', '\xAD', '\xAB', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xAE', '\x3', 
		'\x2', '\x2', '\x2', '\xAE', '\xB0', '\x3', '\x2', '\x2', '\x2', '\xAF', 
		'\xA4', '\x3', '\x2', '\x2', '\x2', '\xAF', '\xA8', '\x3', '\x2', '\x2', 
		'\x2', '\xB0', '\x18', '\x3', '\x2', '\x2', '\x2', '\xB1', '\xB2', '\x5', 
		'\x17', '\f', '\x2', '\xB2', '\xB3', '\a', '+', '\x2', '\x2', '\xB3', 
		'\xB4', '\x5', '\x11', '\t', '\x2', '\xB4', '\x1A', '\x3', '\x2', '\x2', 
		'\x2', '\xB5', '\xB6', '\a', '.', '\x2', '\x2', '\xB6', '\x1C', '\x3', 
		'\x2', '\x2', '\x2', '\xB7', '\xB8', '\a', '\f', '\x2', '\x2', '\xB8', 
		'\xB9', '\x3', '\x2', '\x2', '\x2', '\xB9', '\xBA', '\b', '\xF', '\x2', 
		'\x2', '\xBA', '\x1E', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xBC', '\a', 
		'\xF', '\x2', '\x2', '\xBC', '\xBD', '\x3', '\x2', '\x2', '\x2', '\xBD', 
		'\xBE', '\b', '\x10', '\x2', '\x2', '\xBE', ' ', '\x3', '\x2', '\x2', 
		'\x2', '\xBF', '\xC0', '\a', '\v', '\x2', '\x2', '\xC0', '\xC1', '\x3', 
		'\x2', '\x2', '\x2', '\xC1', '\xC2', '\b', '\x11', '\x2', '\x2', '\xC2', 
		'\"', '\x3', '\x2', '\x2', '\x2', '\n', '\x2', '\x90', '\x98', '\x9C', 
		'\xA1', '\xA6', '\xAD', '\xAF', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
